name: riverflow
description: A library to parse, extract and/or ETL data from HTML document and many others.
version: 1.1.4
homepage: https://github.com/andy1xx8/riverflow-dart
repository: https://github.com/andy1xx8/riverflow-dart

environment:
  sdk: ">=2.12.0 <=4.0.0"

dependencies:
  dolumns: ^2.0.1
  html: ^0.15.4
  intl: ^0.19.0
  timezone: ^0.9.4

dev_dependencies:
  http: ^1.2.2
  pedantic_mono: ^1.27.0
  resource_portable: ^3.1.0
  test: ^1.25.8
