name: riverflow
description: A library to parse, extract and/or ETL data from difference sources. such as HTML document.
version: 1.0.4
homepage: https://github.com/andy1xx8/riverflow-dart
repository: https://github.com/andy1xx8/riverflow-dart

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  intl: ^0.17.0
  timezone: ^0.5.7
  html: ^0.15.0
  url: ^2.0.0
  dolumns: ^1.2.0

dev_dependencies:
  http: ^0.12.2
  pedantic: ^1.9.0
  test: ^1.14.4
  resource: ^2.1.7
